In [ ]:
#Import Packages
from pathlib import Path
import pandas as pd

#Set file paths
root_fldr = Path.cwd().parent
raw_fldr = root_fldr/"data"/"raw"

raw_burns = raw_fldr/"Prescribed_Burns_data.xlsx"

#Read in burn file
prescribed_burns = pd.read_excel(raw_burns)

In [28]:
prescribed_burns.head()

,OBJECTID,YEAR_,STATE,AGENCY,UNIT_ID,TREATMENT_ID,TREATMENT_NAME,TREATMENT_TYPE,START_DATE,END_DATE,TREATED_AC,GIS_ACRES,RX_CONSUM,PRE_CON_CLASS,POST_CON_CLASS,Shape_Length,Shape_Area
0,1,2025.0,CA,BLM,CND,38441,BIL312D Stornetta Rx_FY25,3.0,2024-10-01,2025-02-01,15.0,14.621698,3.0,NaN,NaN,1104.323979,59171.913798
1,2,2025.0,CA,BLM,NOD,45361,BIL312D_FY25_Butte Pile RX,3.0,2024-10-01,2025-02-01,50.0,49.999985,4.0,NaN,NaN,1799.301659,202342.766575
2,3,2025.0,CA,BLM,NOD,38421,BIL312D_FY25_North Horse Pile RX,3.0,2025-02-10,2025-02-12,229.0,228.603134,4.0,NaN,NaN,5386.383188,925124.048407
3,4,2025.0,CA,BLM,NOD,40041,BIL312D_AGFO_WUI_Machine_Pile_Burn,3.0,2024-10-01,2025-02-13,116.0,116.124580,4.0,NaN,NaN,3960.591710,469939.500485
4,5,2025.0,CA,BLM,CND,41684,Black Forest Rx_FY25,3.0,2024-10-01,2025-03-25,25.0,25.118351,4.0,NaN,NaN,3452.593270,101650.358387

In [29]:
prescribed_burns.columns

Index(['OBJECTID', 'YEAR_', 'STATE', 'AGENCY', 'UNIT_ID', 'TREATMENT_ID',
       'TREATMENT_NAME', 'TREATMENT_TYPE', 'START_DATE', 'END_DATE',
       'TREATED_AC', 'GIS_ACRES', 'RX_CONSUM', 'PRE_CON_CLASS',
       'POST_CON_CLASS', 'Shape_Length', 'Shape_Area'],
      dtype='str')

In [51]:
# Check missing values
prescribed_burns.isna().mean().sort_values()*100

OBJECTID           0.000000
STATE              0.000000
AGENCY             0.000000
Shape_Length       0.000000
Shape_Area         0.000000
GIS_ACRES          0.016701
UNIT_ID            0.150313
YEAR_              0.175365
TREATMENT_ID       3.941545
TREATED_AC         6.555324
TREATMENT_NAME    13.210856
START_DATE        14.805846
END_DATE          16.475992
TREATMENT_TYPE    17.661795
RX_CONSUM         90.972860
PRE_CON_CLASS     95.791232
POST_CON_CLASS    95.791232
dtype: float64

Columns with over 90% missing values will not be useful for analysis, so those columns will not be analyzed. Year is necessary for analysis, so the few rows with no year will  be dropped.

In [52]:
#Cleaning
prescribed_burns_cleaned = (
    prescribed_burns
    .dropna(subset=["YEAR_"])
    .drop(columns = ["OBJECTID", "STATE", "UNIT_ID", "TREATMENT_ID", "RX_CONSUM", "PRE_CON_CLASS", "POST_CON_CLASS"])
    .rename(columns = {
            "YEAR_" : "year",
            "AGENCY" : "agency",
            "TREATMENT_NAME" : "burn_name",
            "TREATMENT_TYPE" : "treatment_type",
            "START_DATE" : "start_date",
            "END_DATE" : "end_date",
            "TREATED_AC" : "acres_treated",
            "GIS_ACRES" : "gis_acres_treated"
            })
    .assign(
        year=lambda df: df["year"].astype(int)
    )
)

In [53]:
prescribed_burns_cleaned.head()

,year,agency,burn_name,treatment_type,start_date,end_date,acres_treated,gis_acres_treated,Shape_Length,Shape_Area
0,2025,BLM,BIL312D Stornetta Rx_FY25,3.0,2024-10-01,2025-02-01,15.0,14.621698,1104.323979,59171.913798
1,2025,BLM,BIL312D_FY25_Butte Pile RX,3.0,2024-10-01,2025-02-01,50.0,49.999985,1799.301659,202342.766575
2,2025,BLM,BIL312D_FY25_North Horse Pile RX,3.0,2025-02-10,2025-02-12,229.0,228.603134,5386.383188,925124.048407
3,2025,BLM,BIL312D_AGFO_WUI_Machine_Pile_Burn,3.0,2024-10-01,2025-02-13,116.0,116.124580,3960.591710,469939.500485
4,2025,BLM,Black Forest Rx_FY25,3.0,2024-10-01,2025-03-25,25.0,25.118351,3452.593270,101650.358387