In [1]:
#Import Packages
from pathlib import Path
import pandas as pd

#Set file paths
root_fldr = Path.cwd().parent
raw_fldr = root_fldr/"data"/"raw"

raw_burns = raw_fldr/"Prescribed_Burns_data.xlsx"
raw_invasives = raw_fldr/"inaturalist_invasives.csv"

print(root_fldr)
print(raw_burns)
print(raw_invasives)

c:\Users\ldw62\Desktop\Woock-Goozman-Chu\Goozman-Woock-Chu
c:\Users\ldw62\Desktop\Woock-Goozman-Chu\Goozman-Woock-Chu\data\raw\Prescribed_Burns_data.xlsx
c:\Users\ldw62\Desktop\Woock-Goozman-Chu\Goozman-Woock-Chu\data\raw\inaturalist_invasives.csv

In [2]:
#Read in burn file
prescribed_burns = pd.read_excel(raw_burns)
prescribed_burns.head()

,OBJECTID,YEAR_,STATE,AGENCY,UNIT_ID,TREATMENT_ID,TREATMENT_NAME,TREATMENT_TYPE,START_DATE,END_DATE,TREATED_AC,GIS_ACRES,RX_CONSUM,PRE_CON_CLASS,POST_CON_CLASS,Shape_Length,Shape_Area
0,1,2025.0,CA,BLM,CND,38441,BIL312D Stornetta Rx_FY25,3.0,2024-10-01,2025-02-01,15.0,14.621698,3.0,NaN,NaN,1104.323979,59171.913798
1,2,2025.0,CA,BLM,NOD,45361,BIL312D_FY25_Butte Pile RX,3.0,2024-10-01,2025-02-01,50.0,49.999985,4.0,NaN,NaN,1799.301659,202342.766575
2,3,2025.0,CA,BLM,NOD,38421,BIL312D_FY25_North Horse Pile RX,3.0,2025-02-10,2025-02-12,229.0,228.603134,4.0,NaN,NaN,5386.383188,925124.048407
3,4,2025.0,CA,BLM,NOD,40041,BIL312D_AGFO_WUI_Machine_Pile_Burn,3.0,2024-10-01,2025-02-13,116.0,116.124580,4.0,NaN,NaN,3960.591710,469939.500485
4,5,2025.0,CA,BLM,CND,41684,Black Forest Rx_FY25,3.0,2024-10-01,2025-03-25,25.0,25.118351,4.0,NaN,NaN,3452.593270,101650.358387

In [3]:
#Read in invasives file
invasives = pd.read_csv(raw_invasives)
invasives.head()

,id,uuid,observed_on_string,observed_on,created_at,updated_at,quality_grade,license,url,image_url,...,captive_cultivated,oauth_application_id,place_guess,latitude,longitude,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id
0,2579,903406bb-3f9a-4465-b82a-2a8eb0394796,5/9/2009 11:06,5/9/2009,5/9/2009 15:05,5/30/2020 16:27,research,CC0,http://www.inaturalist.org/observations/2579,https://inaturalist-open-data.s3.amazonaws.com...,...,False,NaN,"Lake Temescal Regional Recreation Area, Oaklan...",37.844845,-122.229355,yellow flag,Iris pseudacorus,Yellow Iris,Plantae,47779
1,3184,d9a90ba1-b8b8-4970-bac0-7cd7e2983388,8/2/2009 16:54,8/2/2009,8/10/2009 14:48,12/10/2016 21:57,research,NaN,http://www.inaturalist.org/observations/3184,https://inaturalist-open-data.s3.amazonaws.com...,...,False,NaN,"Santa Clara County, US-CA, US",37.243595,-121.877426,Yellow Starthistle,Centaurea solstitialis,Yellow Star-Thistle,Plantae,52588
2,4151,5bee462e-49e7-45f6-a35b-c530a2e0d02b,12/31/2009 16:59,12/31/2009,1/9/2010 9:26,6/1/2020 13:48,research,NaN,http://www.inaturalist.org/observations/4151,https://static.inaturalist.org/photos/8367/med...,...,False,NaN,"Almaden Quicksilver Park, CA, US",37.205551,-121.879127,poison hemlock,Conium maculatum,poison hemlock,Plantae,52998
3,7583,5b9f5daa-4720-4bba-bdd3-767ef88838e6,6/12/2010,6/12/2010,6/16/2010 18:45,6/2/2020 15:54,research,CC-BY,http://www.inaturalist.org/observations/7583,https://inaturalist-open-data.s3.amazonaws.com...,...,False,NaN,"Sonoma, CA",38.302235,-122.455406,Yellow Starthistle,Centaurea solstitialis,Yellow Star-Thistle,Plantae,52588
4,7589,d1503aa4-9f75-4cd9-9dd0-e3b925a55add,6/12/2010,6/12/2010,6/17/2010 18:38,8/13/2019 23:19,research,CC-BY,http://www.inaturalist.org/observations/7589,https://inaturalist-open-data.s3.amazonaws.com...,...,False,NaN,"Sonoma, CA",38.301674,-122.456612,Tree of heaven,Ailanthus altissima,tree-of-heaven,Plantae,57278

In [4]:
#Dimensions
print(prescribed_burns.shape)
print(invasives.shape)

(11975, 17)
(147426, 25)